function(pillar_detect_compiler)
    set(PILLAR_GNU_LIKE_COMPILERS "GNU" "Clang" "AppleClang" "Intel")
    set(PILLAR_MSVC_LIKE_COMPILERS "MSVC")

    set(PILLAR_IS_GNU_LIKE 0)
    set(PILLAR_IS_MSVC_LIKE 0)

    if(CMAKE_CXX_COMPILER_ID IN_LIST PILLAR_GNU_LIKE_COMPILERS)
        set(PILLAR_IS_GNU_LIKE 1)
    elseif(CMAKE_CXX_COMPILER_ID IN_LIST PILLAR_MSVC_LIKE_COMPILERS)
        set(PILLAR_IS_MSVC_LIKE 1)
    endif()

    set(PILLAR_IS_GNU_LIKE ${PILLAR_IS_GNU_LIKE} PARENT_SCOPE)
    set(PILLAR_IS_MSVC_LIKE ${PILLAR_IS_MSVC_LIKE} PARENT_SCOPE)
endfunction()