set(PILLAR_IS_GNU_LIKE FALSE PARENT_SCOPE)
set(PILLAR_IS_MSVC_LIKE FALSE PARENT_SCOPE)

set(PILLAR_GNU_LIKE_COMPILERS "GNU" "Clang" "AppleClang" "Intel")
set(PILLAR_MSVC_LIKE_COMPILERS "MSVC")

if(CMAKE_CXX_COMPILER_ID IN_LIST PILLAR_GNU_LIKE_COMPILERS)
    set(PILLAR_IS_GNU_LIKE TRUE PARENT_SCOPE)
elseif(CMAKE_CXX_COMPILER_ID IN_LIST PILLAR_MSVC_LIKE_COMPILERS)
    set(PILLAR_IS_MSVC_LIKE TRUE PARENT_SCOPE)
endif()